# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches:
      - dev 
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'headout/helm@master'
      with:
        release: 'unqork-hw'
        namespace: 'default'
        chart: 'hello-world'
        token: '${{ github.token }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONF }}'
