# .github/workflows/deploy.yml
name: Deploy
on: ['push']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'vimeda/helm@v1.6.8'
      with:
        release: 'unqork-hw'
        namespace: 'default'
        chart: 'hello-world'
        token: '${{ github.token }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONF }}'
